### ISSUE TITLE
Compatible freecam mods

### ISSUE THREAD

**Issue by DaniDipp** [Emonadeo/AutoRun#19]
Do you know any freecam mod that AutoRun is compatible with? I'd like to be able to freely fly around while my character continues to walk forwards.
I tried both [Freecam](https://github.com/MinecraftFreecam/Freecam) and [Tweakeroo](https://github.com/maruohon/tweakeroo) without success.

**Comment by emonadeo** [comment]
It's unlikely that there are any Freecam mods that work with this mod due to the way it's structured. AutoRun works by overriding the keyboard input when activated. When you activate it, it basically „locks“ the current movement input.

Without checking, I would guess the AutoRun will toggle the movement of the camera, not the physical player.

I am considering reengineering it so it directly affects the player movement instead of the keyboard inputs. That should automatically make it compatible with any Freecam or Inventory Movement mod (#16), but it's more likely to break between updates.

**Comment by DaniDipp** [comment]
I see, thanks for the info!
