### ISSUE TITLE
Immersive Aircraft Compatibility

### ISSUE THREAD

**Issue by ginsm** [Emonadeo/AutoRun#25]
The aircrafts in Immersive Aircrafts don't seem to work with this mod. I think it'd be pretty convenient if they did. Is there anything you can do on your end or is it something they'd have to do on their end?

**Comment by emonadeo** [comment]
Probably on their end. Although I don't provide an Interface at the moment (this may change in the future[^1]), AutoRun should „just work“ with other vehicle mods.

I am using a mixin to override `pressingForward`, `pressingBack`, `pressingLeft` and `pressingRight` (See [AutoRunMixin.java](https://github.com/emonadeo/AutoRun/blob/1.21/src/client/java/com/emonadeo/autorun/mixin/client/AutoRunMixin.java)). As such anything using those keybindings will also be affected by Auto-Run, including boats and horses.

In [their source code](https://github.com/Luke100000/ImmersiveAircraft/blob/1.20.1/common/src/main/java/immersive_aircraft/client/KeyBindings.java) it looks like they are creating extra movement keybindings rather than using the vanilla `pressingForward` etc., making it fundamentally incompatible with this mod. I am not sure what the reason is behind it, but in the current state of AutoRun, this is a „won't fix“ for me, sorry.

[^1]: I am considering fundamentally reengineering this mod, so it allows for more fine-grained control over the auto-run behaviour of different vehicles. I am aware that directly coupling this to `pressingForward` etc is really unflexible. (See also: #19)
